### ISSUE TITLE
请问如何设置节点的颜色？

### ISSUE THREAD

**Issue by Lonfar** [funny-cat-happy/joplin-plugin-TimelineRender#6]
请问如何设置节点的颜色？

**Comment by funny-cat-happy** [comment]
open the menu above Tools->Options->Appearance->Show Advanced Settings->Custom stylesheet rendered Markdown
copy the following text to the bottom of the file
```css
.timeline-dot-past {
  background: #148b82;
}
.timeline-dot-current {
  background: #f0a80d;
}
.timeline-dot-future {
  background: #f55104;
}
```
save the file and reboot your joplin
